#!/bin/sh

which browserify > /dev/null
if [ "$?" = "1" ]; then
	echo "Browserify not found. Please install from npm via:"
	echo "npm install -g browserify"
	exit 1
fi
browserify "lib/client.js" "lib/client_demo.js" -o "runtime/worker.js"
